world:
  width: 200
  height: 150

sim:
  seed: 12345
  render_every: 2
  max_plants: 4000
  stats_interval: 10
  initial_plants: 100
  reproduction_chance: 0.05
  max_age: 1000

plants:
  # Ranges for initializing new genomes uniformly [lo, hi]
  init:
    temp_optimum: [0.0, 1.0]
    temp_tolerance: [0.1, 0.5]
    shade_tolerance: [0.0, 1.0]
    water_efficiency: [0.0, 1.0]
    growth_rate: [0.2, 0.8]
    photosynthesis_rate: [0.2, 0.8]
    maintenance_cost: [0.05, 0.2]
    max_size: [5.0, 20.0]
    repro_threshold: [3.0, 10.0]
    seed_dispersal: [1.0, 6.0]
    seed_energy: [0.5, 2.5]
    initial_energy: [1.0, 3.0]

  # Mutation parameters and clipping bounds
  mutation:
    rate: 0.02
    sigma_traits: 0.1
    sigma_max_size: 1.0
    sigma_seed_energy: 0.2
    clip_traits: [0.01, 1.0]
    clip_max_size: [1.0, 50.0]
    clip_seed_energy: [0.5, 5.0]

  # Physiology constants used in growth/energy flows
  physiology:
    photo_base_mult: 2.0
    nutrient_effect_mult: 2.0
    nutrient_cap: 1.0
    nutrient_consumption_base: 0.01
    water_use_base: 0.02
    shade_cast_coeff: 0.5
    shade_cap: 0.9
    maintenance_size_mult: 2.0
    water_eff_epsilon: 0.01
    low_light_threshold: 0.3
    nutrient_return_mult: 0.3

  # Species clustering settings
  species:
    distance_threshold: 0.5

view:
  window_width: 640
  window_height: 640
  fps: 30
  title: "Cellular Life: Plants MVP"
