world:
  width: 200
  height: 150
  torus: true
  regrow_rate: 0.008
  diffusion_rate: 0.05
  max_resource: 1.0
  season:
    amplitude: 0.3
    period_steps: 2000
  disturbance:
    prob_per_step: 0.01
    patch_radius: 8
    magnitude: 1.0
    mode: reset
sim:
  steps: 200000
  render_every: 1
  log_every: 50
  seed: 12345
agents:
  init_population: 400
  max_population: 2000
  init_energy: 6.0
  metabolism: 0.075
  move_cost: 0.015
  graze_rate: 0.05
  graze_efficiency: 1.0
  spawn_attempts: 5
view:
  cell_size: 4
  fps: 60
  show_grid: false
  title: "Cellular Life: Stage 1"
